// <auto-generated />
namespace WP_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WP_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WP_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201809150736279_WP_1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
