// <auto-generated />
namespace WP_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomField_FieldValue_Item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomField_FieldValue_Item));
        
        string IMigrationMetadata.Id
        {
            get { return "201809200718279_CustomField_FieldValue_Item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
